<a href="https://colab.research.google.com/github/Pedro4Albuquerque/Processamento-de-Linguagem-Natural/blob/main/Aula05_atividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bibliotecas

In [4]:
!pip install -q spacy pandas
!python -m spacy download pt_core_news_sm -q

import spacy
import pandas as pd
from spacy import displacy

nlp = spacy.load("pt_core_news_sm")

print("Ambiente configurado com sucesso.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 68.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Ambiente configurado com sucesso.

In [6]:
import nltk


from nltk.stem import RSLPStemmer

# Baixa os arquivos necessários para o stemmer em português
nltk.download("rslp")

# Frase do exercício
frase_exercicio = "O proprietário alugou a casa para a família rapidamente."

doc = nlp(frase_exercicio)

[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!

# Passo 1: Tokenização

In [7]:

tokens = [token.text for token in doc]

print("PASSO 1 - TOKENIZAÇÃO")
print(tokens)

PASSO 1 - TOKENIZAÇÃO
['O', 'proprietário', 'alugou', 'a', 'casa', 'para', 'a', 'família', 'rapidamente', '.']

# Passo 2: Remoção de pontuação e stopwords

In [8]:
tokens_filtrados = [
    token.text
    for token in doc
    if not token.is_punct and not token.is_stop
]

print("\nPASSO 2 - SEM PONTUAÇÃO E STOPWORDS")
print(tokens_filtrados)

PASSO 2 - SEM PONTUAÇÃO E STOPWORDS
['proprietário', 'alugou', 'casa', 'família', 'rapidamente']

# Passo 3: Stemming e Lematização

In [9]:

stemmer = RSLPStemmer()

dados = []

for token in doc:
    if not token.is_punct and not token.is_stop:
        dados.append({
            "Palavra": token.text,
            "Stemming": stemmer.stem(token.text.lower()),
            "Lematização": token.lemma_
        })

tabela = pd.DataFrame(dados)

print("\nPASSO 3 - STEMMING E LEMATIZAÇÃO")
display(tabela)

PASSO 3 - STEMMING E LEMATIZAÇÃO

        Palavra  Stemming   Lematização
0  proprietário  propriet  proprietário
1        alugou      alug        alugar
2          casa       cas          casa
3       família     famíl       família
4   rapidamente     rapid   rapidamente

# Passo 4: POS Tagging

In [10]:
dados_pos = []

for token in doc:
    if not token.is_punct:
        dados_pos.append({
            "Palavra": token.text,
            "POS": token.pos_,
            "Tag detalhada": token.tag_
        })

tabela_pos = pd.DataFrame(dados_pos)

print("\nPASSO 4 - POS TAGGING")
display(tabela_pos)

PASSO 4 - POS TAGGING

        Palavra   POS Tag detalhada
0             O   DET           DET
1  proprietário  NOUN          NOUN
2        alugou  VERB          VERB
3             a   DET           DET
4          casa  NOUN          NOUN
5          para   ADP           ADP
6             a   DET           DET
7       família  NOUN          NOUN
8   rapidamente   ADV           ADV

# Passo 5: Sintagma Nominal e Sintagma Verbal

In [11]:

print("\nPASSO 5 - SINTAGMAS")

print("\nSintagmas Nominais:")
for chunk in doc.noun_chunks:
    print("-", chunk.text)

print("\nSintagmas Verbais:")
for token in doc:
    if token.pos_ == "VERB":
        palavras = sorted(
            list(token.subtree),
            key=lambda x: x.i
        )

        sintagma_verbal = " ".join(
            palavra.text for palavra in palavras
        )

        print("-", sintagma_verbal)

PASSO 5 - SINTAGMAS

Sintagmas Nominais:
- O proprietário
- a casa
- a família

Sintagmas Verbais:
- O proprietário alugou a casa para a família rapidamente .

# Passo 6: Similaridade entre duas palavras

In [14]:
palavra1 = nlp("casa")
palavra2 = nlp("família")

similaridade = palavra1.similarity(palavra2)

print("\nPASSO 6 - SIMILARIDADE")
print(
    f"Similaridade entre 'casa' e 'família': "
    f"{similaridade:.3f}"
);

PASSO 6 - SIMILARIDADE
Similaridade entre 'casa' e 'família': 0.311

/tmp/ipykernel_884/553439963.py:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  similaridade = palavra1.similarity(palavra2)